# Generated by Django 4.1.3 on 2022-11-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='fabricante',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publishing_company',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
    ]
